syntax = "proto3";

import "common.proto";
import "google/protobuf/struct.proto";

package grpcagent;

message Asset {
  CommonResponse common = 1;
  uint64 thread_id = 2;
  google.protobuf.Struct metadata = 3;
  string data = 4;
  bool complete = 5;
  uint64 duration = 6;  // Duration of the profile in milliseconds
  double start_ts = 7;  // Timestamp when the profile was taken in milliseconds from epoch
  double end_ts = 8;    // Timestamp when the profile was completed in milliseconds from epoch
}