// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: asset.proto
// Protobuf C++ Version: 7.34.0

#ifndef asset_2eproto_2epb_2eh
#define asset_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "common.pb.h"
#include "google/protobuf/struct.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_asset_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_asset_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_asset_2eproto;
}  // extern "C"
namespace grpcagent {
class Asset;
struct AssetDefaultTypeInternal;
extern AssetDefaultTypeInternal _Asset_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Asset_class_data_;
}  // namespace grpcagent
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace grpcagent {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED Asset final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:grpcagent.Asset) */ {
 public:
  inline Asset() : Asset(nullptr) {}
  ~Asset() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Asset* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Asset));
  }
#endif

  template <typename = void>
  explicit constexpr Asset(::google::protobuf::internal::ConstantInitialized);

  inline Asset(const Asset& from) : Asset(nullptr, from) {}
  inline Asset(Asset&& from) noexcept
      : Asset(nullptr, ::std::move(from)) {}
  inline Asset& operator=(const Asset& from) {
    CopyFrom(from);
    return *this;
  }
  inline Asset& operator=(Asset&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const Asset& default_instance() {
    return *reinterpret_cast<const Asset*>(
        &_Asset_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Asset& a, Asset& b) { a.Swap(&b); }
  inline void Swap(Asset* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Asset* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] Asset* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Asset>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Asset& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Asset& from) { Asset::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Asset* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "grpcagent.Asset"; }

  explicit Asset(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Asset(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Asset& from);
  Asset(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Asset&& from) noexcept
      : Asset(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDataFieldNumber = 4,
    kCommonFieldNumber = 1,
    kMetadataFieldNumber = 3,
    kThreadIdFieldNumber = 2,
    kDurationFieldNumber = 6,
    kStartTsFieldNumber = 7,
    kEndTsFieldNumber = 8,
    kCompleteFieldNumber = 5,
  };
  // string data = 4;
  void clear_data() ;
  [[nodiscard]] const ::std::string& data() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_data();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_data();
  void set_allocated_data(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_data() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_data(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_data();

  public:
  // .grpcagent.CommonResponse common = 1;
  [[nodiscard]] bool has_common()
      const;
  void clear_common() ;
  [[nodiscard]] const ::grpcagent::CommonResponse& common() const;
  [[nodiscard]] ::grpcagent::CommonResponse* PROTOBUF_NULLABLE release_common();
  ::grpcagent::CommonResponse* PROTOBUF_NONNULL mutable_common();
  void set_allocated_common(::grpcagent::CommonResponse* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_common(::grpcagent::CommonResponse* PROTOBUF_NULLABLE value);
  ::grpcagent::CommonResponse* PROTOBUF_NULLABLE unsafe_arena_release_common();

  private:
  const ::grpcagent::CommonResponse& _internal_common() const;
  ::grpcagent::CommonResponse* PROTOBUF_NONNULL _internal_mutable_common();

  public:
  // .google.protobuf.Struct metadata = 3;
  [[nodiscard]] bool has_metadata()
      const;
  void clear_metadata() ;
  [[nodiscard]] const ::google::protobuf::Struct& metadata() const;
  [[nodiscard]] ::google::protobuf::Struct* PROTOBUF_NULLABLE release_metadata();
  ::google::protobuf::Struct* PROTOBUF_NONNULL mutable_metadata();
  void set_allocated_metadata(::google::protobuf::Struct* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_metadata(::google::protobuf::Struct* PROTOBUF_NULLABLE value);
  ::google::protobuf::Struct* PROTOBUF_NULLABLE unsafe_arena_release_metadata();

  private:
  const ::google::protobuf::Struct& _internal_metadata() const;
  ::google::protobuf::Struct* PROTOBUF_NONNULL _internal_mutable_metadata();

  public:
  // uint64 thread_id = 2;
  void clear_thread_id() ;
  [[nodiscard]] ::uint64_t thread_id() const;
  void set_thread_id(::uint64_t value);

  private:
  ::uint64_t _internal_thread_id() const;
  void _internal_set_thread_id(::uint64_t value);

  public:
  // uint64 duration = 6;
  void clear_duration() ;
  [[nodiscard]] ::uint64_t duration() const;
  void set_duration(::uint64_t value);

  private:
  ::uint64_t _internal_duration() const;
  void _internal_set_duration(::uint64_t value);

  public:
  // double start_ts = 7;
  void clear_start_ts() ;
  [[nodiscard]] double start_ts() const;
  void set_start_ts(double value);

  private:
  double _internal_start_ts() const;
  void _internal_set_start_ts(double value);

  public:
  // double end_ts = 8;
  void clear_end_ts() ;
  [[nodiscard]] double end_ts() const;
  void set_end_ts(double value);

  private:
  double _internal_end_ts() const;
  void _internal_set_end_ts(double value);

  public:
  // bool complete = 5;
  void clear_complete() ;
  [[nodiscard]] bool complete() const;
  void set_complete(bool value);

  private:
  bool _internal_complete() const;
  void _internal_set_complete(bool value);

  public:
  // @@protoc_insertion_point(class_scope:grpcagent.Asset)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 8,
                                   2, 36,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Asset& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr data_;
    ::grpcagent::CommonResponse* PROTOBUF_NULLABLE common_;
    ::google::protobuf::Struct* PROTOBUF_NULLABLE metadata_;
    ::uint64_t thread_id_;
    ::uint64_t duration_;
    double start_ts_;
    double end_ts_;
    bool complete_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_asset_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Asset_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Asset

// .grpcagent.CommonResponse common = 1;
inline bool Asset::has_common() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.common_ != nullptr);
  return value;
}
inline const ::grpcagent::CommonResponse& Asset::_internal_common() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::grpcagent::CommonResponse* p = _impl_.common_;
  return p != nullptr ? *p : reinterpret_cast<const ::grpcagent::CommonResponse&>(::grpcagent::_CommonResponse_default_instance_);
}
inline const ::grpcagent::CommonResponse& Asset::common() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:grpcagent.Asset.common)
  return _internal_common();
}
inline void Asset::unsafe_arena_set_allocated_common(
    ::grpcagent::CommonResponse* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.common_);
  }
  _impl_.common_ = reinterpret_cast<::grpcagent::CommonResponse*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:grpcagent.Asset.common)
}
inline ::grpcagent::CommonResponse* PROTOBUF_NULLABLE Asset::release_common() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::grpcagent::CommonResponse* released = _impl_.common_;
  _impl_.common_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::grpcagent::CommonResponse* PROTOBUF_NULLABLE Asset::unsafe_arena_release_common() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:grpcagent.Asset.common)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::grpcagent::CommonResponse* temp = _impl_.common_;
  _impl_.common_ = nullptr;
  return temp;
}
inline ::grpcagent::CommonResponse* PROTOBUF_NONNULL Asset::_internal_mutable_common() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.common_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::grpcagent::CommonResponse>(GetArena());
    _impl_.common_ = reinterpret_cast<::grpcagent::CommonResponse*>(p);
  }
  return _impl_.common_;
}
inline ::grpcagent::CommonResponse* PROTOBUF_NONNULL Asset::mutable_common()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::grpcagent::CommonResponse* _msg = _internal_mutable_common();
  // @@protoc_insertion_point(field_mutable:grpcagent.Asset.common)
  return _msg;
}
inline void Asset::set_allocated_common(::grpcagent::CommonResponse* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.common_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.common_ = reinterpret_cast<::grpcagent::CommonResponse*>(value);
  // @@protoc_insertion_point(field_set_allocated:grpcagent.Asset.common)
}

// uint64 thread_id = 2;
inline void Asset::clear_thread_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.thread_id_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::uint64_t Asset::thread_id() const {
  // @@protoc_insertion_point(field_get:grpcagent.Asset.thread_id)
  return _internal_thread_id();
}
inline void Asset::set_thread_id(::uint64_t value) {
  _internal_set_thread_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:grpcagent.Asset.thread_id)
}
inline ::uint64_t Asset::_internal_thread_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.thread_id_;
}
inline void Asset::_internal_set_thread_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.thread_id_ = value;
}

// .google.protobuf.Struct metadata = 3;
inline bool Asset::has_metadata() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  PROTOBUF_ASSUME(!value || _impl_.metadata_ != nullptr);
  return value;
}
inline const ::google::protobuf::Struct& Asset::_internal_metadata() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::Struct* p = _impl_.metadata_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::Struct&>(::google::protobuf::_Struct_default_instance_);
}
inline const ::google::protobuf::Struct& Asset::metadata() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:grpcagent.Asset.metadata)
  return _internal_metadata();
}
inline void Asset::unsafe_arena_set_allocated_metadata(
    ::google::protobuf::Struct* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.metadata_);
  }
  _impl_.metadata_ = reinterpret_cast<::google::protobuf::Struct*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:grpcagent.Asset.metadata)
}
inline ::google::protobuf::Struct* PROTOBUF_NULLABLE Asset::release_metadata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::google::protobuf::Struct* released = _impl_.metadata_;
  _impl_.metadata_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::google::protobuf::Struct* PROTOBUF_NULLABLE Asset::unsafe_arena_release_metadata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:grpcagent.Asset.metadata)

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::google::protobuf::Struct* temp = _impl_.metadata_;
  _impl_.metadata_ = nullptr;
  return temp;
}
inline ::google::protobuf::Struct* PROTOBUF_NONNULL Asset::_internal_mutable_metadata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.metadata_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::Struct>(GetArena());
    _impl_.metadata_ = reinterpret_cast<::google::protobuf::Struct*>(p);
  }
  return _impl_.metadata_;
}
inline ::google::protobuf::Struct* PROTOBUF_NONNULL Asset::mutable_metadata()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::google::protobuf::Struct* _msg = _internal_mutable_metadata();
  // @@protoc_insertion_point(field_mutable:grpcagent.Asset.metadata)
  return _msg;
}
inline void Asset::set_allocated_metadata(::google::protobuf::Struct* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.metadata_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }

  _impl_.metadata_ = reinterpret_cast<::google::protobuf::Struct*>(value);
  // @@protoc_insertion_point(field_set_allocated:grpcagent.Asset.metadata)
}

// string data = 4;
inline void Asset::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& Asset::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:grpcagent.Asset.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Asset::set_data(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.data_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:grpcagent.Asset.data)
}
inline ::std::string* PROTOBUF_NONNULL Asset::mutable_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:grpcagent.Asset.data)
  return _s;
}
inline const ::std::string& Asset::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void Asset::_internal_set_data(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Asset::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Asset::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:grpcagent.Asset.data)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.data_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.data_.Set("", GetArena());
  }
  return released;
}
inline void Asset::set_allocated_data(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:grpcagent.Asset.data)
}

// bool complete = 5;
inline void Asset::clear_complete() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.complete_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline bool Asset::complete() const {
  // @@protoc_insertion_point(field_get:grpcagent.Asset.complete)
  return _internal_complete();
}
inline void Asset::set_complete(bool value) {
  _internal_set_complete(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:grpcagent.Asset.complete)
}
inline bool Asset::_internal_complete() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.complete_;
}
inline void Asset::_internal_set_complete(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.complete_ = value;
}

// uint64 duration = 6;
inline void Asset::clear_duration() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.duration_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::uint64_t Asset::duration() const {
  // @@protoc_insertion_point(field_get:grpcagent.Asset.duration)
  return _internal_duration();
}
inline void Asset::set_duration(::uint64_t value) {
  _internal_set_duration(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:grpcagent.Asset.duration)
}
inline ::uint64_t Asset::_internal_duration() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.duration_;
}
inline void Asset::_internal_set_duration(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.duration_ = value;
}

// double start_ts = 7;
inline void Asset::clear_start_ts() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.start_ts_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline double Asset::start_ts() const {
  // @@protoc_insertion_point(field_get:grpcagent.Asset.start_ts)
  return _internal_start_ts();
}
inline void Asset::set_start_ts(double value) {
  _internal_set_start_ts(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:grpcagent.Asset.start_ts)
}
inline double Asset::_internal_start_ts() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.start_ts_;
}
inline void Asset::_internal_set_start_ts(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.start_ts_ = value;
}

// double end_ts = 8;
inline void Asset::clear_end_ts() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.end_ts_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline double Asset::end_ts() const {
  // @@protoc_insertion_point(field_get:grpcagent.Asset.end_ts)
  return _internal_end_ts();
}
inline void Asset::set_end_ts(double value) {
  _internal_set_end_ts(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:grpcagent.Asset.end_ts)
}
inline double Asset::_internal_end_ts() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.end_ts_;
}
inline void Asset::_internal_set_end_ts(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.end_ts_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace grpcagent


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // asset_2eproto_2epb_2eh
