// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: info.proto
// Protobuf C++ Version: 7.34.0

#ifndef info_2eproto_2epb_2eh
#define info_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_type_handler.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field.h"
#include "google/protobuf/unknown_field_set.h"
#include "common.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_info_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_info_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_info_2eproto;
}  // extern "C"
namespace grpcagent {
class InfoBody;
struct InfoBodyDefaultTypeInternal;
extern InfoBodyDefaultTypeInternal _InfoBody_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull InfoBody_class_data_;
class InfoBody_VersionsEntry_DoNotUse;
struct InfoBody_VersionsEntry_DoNotUseDefaultTypeInternal;
extern InfoBody_VersionsEntry_DoNotUseDefaultTypeInternal _InfoBody_VersionsEntry_DoNotUse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull InfoBody_VersionsEntry_DoNotUse_class_data_;
class InfoEvent;
struct InfoEventDefaultTypeInternal;
extern InfoEventDefaultTypeInternal _InfoEvent_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull InfoEvent_class_data_;
}  // namespace grpcagent
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace grpcagent {

// ===================================================================


// -------------------------------------------------------------------

class PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED InfoBody_VersionsEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<::std::string, ::std::string,
                             ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                             ::google::protobuf::internal::WireFormatLite::TYPE_STRING> {
 public:
  using SuperType =
      ::google::protobuf::internal::MapEntry<::std::string, ::std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>;
  InfoBody_VersionsEntry_DoNotUse();
  template <typename = void>
  explicit constexpr InfoBody_VersionsEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized);
  explicit InfoBody_VersionsEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_default_instance() {
    return &_InfoBody_VersionsEntry_DoNotUse_default_instance_;
  }


  static constexpr auto InternalGenerateClassData_();

 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_info_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 49,
                                   2>
      _table_;

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
extern const ::google::protobuf::internal::ClassDataFull InfoBody_VersionsEntry_DoNotUse_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED InfoBody final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:grpcagent.InfoBody) */ {
 public:
  inline InfoBody() : InfoBody(nullptr) {}
  ~InfoBody() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(InfoBody* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(InfoBody));
  }
#endif

  template <typename = void>
  explicit constexpr InfoBody(::google::protobuf::internal::ConstantInitialized);

  inline InfoBody(const InfoBody& from) : InfoBody(nullptr, from) {}
  inline InfoBody(InfoBody&& from) noexcept
      : InfoBody(nullptr, ::std::move(from)) {}
  inline InfoBody& operator=(const InfoBody& from) {
    CopyFrom(from);
    return *this;
  }
  inline InfoBody& operator=(InfoBody&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const InfoBody& default_instance() {
    return *reinterpret_cast<const InfoBody*>(
        &_InfoBody_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(InfoBody& a, InfoBody& b) { a.Swap(&b); }
  inline void Swap(InfoBody* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InfoBody* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] InfoBody* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<InfoBody>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const InfoBody& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const InfoBody& from) { InfoBody::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(InfoBody* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "grpcagent.InfoBody"; }

  explicit InfoBody(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  InfoBody(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const InfoBody& from);
  InfoBody(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, InfoBody&& from) noexcept
      : InfoBody(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTagsFieldNumber = 13,
    kAppFieldNumber = 1,
    kArchFieldNumber = 2,
    kCpuModelFieldNumber = 4,
    kExecPathFieldNumber = 5,
    kHostnameFieldNumber = 6,
    kIdFieldNumber = 7,
    kMainFieldNumber = 8,
    kNodeEnvFieldNumber = 9,
    kPlatformFieldNumber = 11,
    kAppVersionFieldNumber = 17,
    kCpuCoresFieldNumber = 3,
    kPidFieldNumber = 10,
    kProcessStartFieldNumber = 12,
    kTotalMemFieldNumber = 14,
    kKernelVersionFieldNumber = 16,
    kVersionsFieldNumber = 15,
  };
  // repeated string tags = 13;
  [[nodiscard]] int tags_size()
      const;
  private:
  int _internal_tags_size() const;

  public:
  void clear_tags() ;
  [[nodiscard]] const ::std::string& tags(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_tags(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_tags(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_tags();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_tags(Arg_&& value, Args_... args);
  [[nodiscard]] const ::google::protobuf::RepeatedPtrField<::std::string>&
  tags() const;
  [[nodiscard]] ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
  mutable_tags();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_tags() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_tags();

  public:
  // string app = 1;
  void clear_app() ;
  [[nodiscard]] const ::std::string& app() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_app(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_app();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_app();
  void set_allocated_app(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_app() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_app(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_app();

  public:
  // string arch = 2;
  void clear_arch() ;
  [[nodiscard]] const ::std::string& arch() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_arch(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_arch();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_arch();
  void set_allocated_arch(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_arch() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_arch(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_arch();

  public:
  // string cpuModel = 4;
  void clear_cpumodel() ;
  [[nodiscard]] const ::std::string& cpumodel() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_cpumodel(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_cpumodel();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_cpumodel();
  void set_allocated_cpumodel(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_cpumodel() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_cpumodel(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_cpumodel();

  public:
  // string execPath = 5;
  void clear_execpath() ;
  [[nodiscard]] const ::std::string& execpath() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_execpath(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_execpath();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_execpath();
  void set_allocated_execpath(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_execpath() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_execpath(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_execpath();

  public:
  // string hostname = 6;
  void clear_hostname() ;
  [[nodiscard]] const ::std::string& hostname() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_hostname(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_hostname();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_hostname();
  void set_allocated_hostname(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_hostname() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_hostname(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_hostname();

  public:
  // string id = 7;
  void clear_id() ;
  [[nodiscard]] const ::std::string& id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_id();
  void set_allocated_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_id();

  public:
  // string main = 8;
  void clear_main() ;
  [[nodiscard]] const ::std::string& main() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_main(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_main();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_main();
  void set_allocated_main(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_main() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_main(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_main();

  public:
  // string nodeEnv = 9;
  void clear_nodeenv() ;
  [[nodiscard]] const ::std::string& nodeenv() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_nodeenv(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_nodeenv();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_nodeenv();
  void set_allocated_nodeenv(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_nodeenv() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_nodeenv(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_nodeenv();

  public:
  // string platform = 11;
  void clear_platform() ;
  [[nodiscard]] const ::std::string& platform() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_platform(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_platform();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_platform();
  void set_allocated_platform(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_platform() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_platform(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_platform();

  public:
  // optional string appVersion = 17;
  [[nodiscard]] bool has_appversion()
      const;
  void clear_appversion() ;
  [[nodiscard]] const ::std::string& appversion() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_appversion(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_appversion();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_appversion();
  void set_allocated_appversion(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_appversion() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_appversion(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_appversion();

  public:
  // uint32 cpuCores = 3;
  void clear_cpucores() ;
  [[nodiscard]] ::uint32_t cpucores() const;
  void set_cpucores(::uint32_t value);

  private:
  ::uint32_t _internal_cpucores() const;
  void _internal_set_cpucores(::uint32_t value);

  public:
  // uint32 pid = 10;
  void clear_pid() ;
  [[nodiscard]] ::uint32_t pid() const;
  void set_pid(::uint32_t value);

  private:
  ::uint32_t _internal_pid() const;
  void _internal_set_pid(::uint32_t value);

  public:
  // uint64 processStart = 12;
  void clear_processstart() ;
  [[nodiscard]] ::uint64_t processstart() const;
  void set_processstart(::uint64_t value);

  private:
  ::uint64_t _internal_processstart() const;
  void _internal_set_processstart(::uint64_t value);

  public:
  // uint64 totalMem = 14;
  void clear_totalmem() ;
  [[nodiscard]] ::uint64_t totalmem() const;
  void set_totalmem(::uint64_t value);

  private:
  ::uint64_t _internal_totalmem() const;
  void _internal_set_totalmem(::uint64_t value);

  public:
  // uint32 kernelVersion = 16;
  void clear_kernelversion() ;
  [[nodiscard]] ::uint32_t kernelversion() const;
  void set_kernelversion(::uint32_t value);

  private:
  ::uint32_t _internal_kernelversion() const;
  void _internal_set_kernelversion(::uint32_t value);

  public:
  // map<string, string> versions = 15;
  [[nodiscard]] int versions_size()
      const;
  private:
  int _internal_versions_size() const;

  public:
  void clear_versions() ;
  [[nodiscard]] const ::google::protobuf::Map<::std::string, ::std::string>& versions() const;
  [[nodiscard]] ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL mutable_versions();

  private:
  const ::google::protobuf::Map<::std::string, ::std::string>& _internal_versions() const;
  ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL _internal_mutable_versions();

  public:
  // @@protoc_insertion_point(class_scope:grpcagent.InfoBody)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<5, 17,
                                   1, 117,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const InfoBody& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<::std::string> tags_;
    ::google::protobuf::internal::ArenaStringPtr app_;
    ::google::protobuf::internal::ArenaStringPtr arch_;
    ::google::protobuf::internal::ArenaStringPtr cpumodel_;
    ::google::protobuf::internal::ArenaStringPtr execpath_;
    ::google::protobuf::internal::ArenaStringPtr hostname_;
    ::google::protobuf::internal::ArenaStringPtr id_;
    ::google::protobuf::internal::ArenaStringPtr main_;
    ::google::protobuf::internal::ArenaStringPtr nodeenv_;
    ::google::protobuf::internal::ArenaStringPtr platform_;
    ::google::protobuf::internal::ArenaStringPtr appversion_;
    ::uint32_t cpucores_;
    ::uint32_t pid_;
    ::uint64_t processstart_;
    ::uint64_t totalmem_;
    ::uint32_t kernelversion_;
    ::google::protobuf::internal::MapField<InfoBody_VersionsEntry_DoNotUse, ::std::string, ::std::string> versions_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_info_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull InfoBody_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED InfoEvent final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:grpcagent.InfoEvent) */ {
 public:
  inline InfoEvent() : InfoEvent(nullptr) {}
  ~InfoEvent() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(InfoEvent* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(InfoEvent));
  }
#endif

  template <typename = void>
  explicit constexpr InfoEvent(::google::protobuf::internal::ConstantInitialized);

  inline InfoEvent(const InfoEvent& from) : InfoEvent(nullptr, from) {}
  inline InfoEvent(InfoEvent&& from) noexcept
      : InfoEvent(nullptr, ::std::move(from)) {}
  inline InfoEvent& operator=(const InfoEvent& from) {
    CopyFrom(from);
    return *this;
  }
  inline InfoEvent& operator=(InfoEvent&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const InfoEvent& default_instance() {
    return *reinterpret_cast<const InfoEvent*>(
        &_InfoEvent_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(InfoEvent& a, InfoEvent& b) { a.Swap(&b); }
  inline void Swap(InfoEvent* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InfoEvent* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] InfoEvent* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<InfoEvent>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const InfoEvent& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const InfoEvent& from) { InfoEvent::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(InfoEvent* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "grpcagent.InfoEvent"; }

  explicit InfoEvent(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  InfoEvent(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const InfoEvent& from);
  InfoEvent(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, InfoEvent&& from) noexcept
      : InfoEvent(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCommonFieldNumber = 1,
    kBodyFieldNumber = 2,
  };
  // .grpcagent.CommonResponse common = 1;
  [[nodiscard]] bool has_common()
      const;
  void clear_common() ;
  [[nodiscard]] const ::grpcagent::CommonResponse& common() const;
  [[nodiscard]] ::grpcagent::CommonResponse* PROTOBUF_NULLABLE release_common();
  ::grpcagent::CommonResponse* PROTOBUF_NONNULL mutable_common();
  void set_allocated_common(::grpcagent::CommonResponse* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_common(::grpcagent::CommonResponse* PROTOBUF_NULLABLE value);
  ::grpcagent::CommonResponse* PROTOBUF_NULLABLE unsafe_arena_release_common();

  private:
  const ::grpcagent::CommonResponse& _internal_common() const;
  ::grpcagent::CommonResponse* PROTOBUF_NONNULL _internal_mutable_common();

  public:
  // .grpcagent.InfoBody body = 2;
  [[nodiscard]] bool has_body()
      const;
  void clear_body() ;
  [[nodiscard]] const ::grpcagent::InfoBody& body() const;
  [[nodiscard]] ::grpcagent::InfoBody* PROTOBUF_NULLABLE release_body();
  ::grpcagent::InfoBody* PROTOBUF_NONNULL mutable_body();
  void set_allocated_body(::grpcagent::InfoBody* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_body(::grpcagent::InfoBody* PROTOBUF_NULLABLE value);
  ::grpcagent::InfoBody* PROTOBUF_NULLABLE unsafe_arena_release_body();

  private:
  const ::grpcagent::InfoBody& _internal_body() const;
  ::grpcagent::InfoBody* PROTOBUF_NONNULL _internal_mutable_body();

  public:
  // @@protoc_insertion_point(class_scope:grpcagent.InfoEvent)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const InfoEvent& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::grpcagent::CommonResponse* PROTOBUF_NULLABLE common_;
    ::grpcagent::InfoBody* PROTOBUF_NULLABLE body_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_info_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull InfoEvent_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// InfoBody

// string app = 1;
inline void InfoBody::clear_app() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.app_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& InfoBody::app() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:grpcagent.InfoBody.app)
  return _internal_app();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void InfoBody::set_app(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.app_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:grpcagent.InfoBody.app)
}
inline ::std::string* PROTOBUF_NONNULL InfoBody::mutable_app()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_app();
  // @@protoc_insertion_point(field_mutable:grpcagent.InfoBody.app)
  return _s;
}
inline const ::std::string& InfoBody::_internal_app() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.app_.Get();
}
inline void InfoBody::_internal_set_app(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.app_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL InfoBody::_internal_mutable_app() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.app_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE InfoBody::release_app() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:grpcagent.InfoBody.app)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.app_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.app_.Set("", GetArena());
  }
  return released;
}
inline void InfoBody::set_allocated_app(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.app_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.app_.IsDefault()) {
    _impl_.app_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:grpcagent.InfoBody.app)
}

// string arch = 2;
inline void InfoBody::clear_arch() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.arch_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& InfoBody::arch() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:grpcagent.InfoBody.arch)
  return _internal_arch();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void InfoBody::set_arch(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.arch_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:grpcagent.InfoBody.arch)
}
inline ::std::string* PROTOBUF_NONNULL InfoBody::mutable_arch()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_arch();
  // @@protoc_insertion_point(field_mutable:grpcagent.InfoBody.arch)
  return _s;
}
inline const ::std::string& InfoBody::_internal_arch() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.arch_.Get();
}
inline void InfoBody::_internal_set_arch(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.arch_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL InfoBody::_internal_mutable_arch() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.arch_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE InfoBody::release_arch() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:grpcagent.InfoBody.arch)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.arch_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.arch_.Set("", GetArena());
  }
  return released;
}
inline void InfoBody::set_allocated_arch(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.arch_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.arch_.IsDefault()) {
    _impl_.arch_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:grpcagent.InfoBody.arch)
}

// uint32 cpuCores = 3;
inline void InfoBody::clear_cpucores() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cpucores_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000800U);
}
inline ::uint32_t InfoBody::cpucores() const {
  // @@protoc_insertion_point(field_get:grpcagent.InfoBody.cpuCores)
  return _internal_cpucores();
}
inline void InfoBody::set_cpucores(::uint32_t value) {
  _internal_set_cpucores(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000800U);
  // @@protoc_insertion_point(field_set:grpcagent.InfoBody.cpuCores)
}
inline ::uint32_t InfoBody::_internal_cpucores() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cpucores_;
}
inline void InfoBody::_internal_set_cpucores(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cpucores_ = value;
}

// string cpuModel = 4;
inline void InfoBody::clear_cpumodel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cpumodel_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::std::string& InfoBody::cpumodel() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:grpcagent.InfoBody.cpuModel)
  return _internal_cpumodel();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void InfoBody::set_cpumodel(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.cpumodel_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:grpcagent.InfoBody.cpuModel)
}
inline ::std::string* PROTOBUF_NONNULL InfoBody::mutable_cpumodel()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_cpumodel();
  // @@protoc_insertion_point(field_mutable:grpcagent.InfoBody.cpuModel)
  return _s;
}
inline const ::std::string& InfoBody::_internal_cpumodel() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cpumodel_.Get();
}
inline void InfoBody::_internal_set_cpumodel(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cpumodel_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL InfoBody::_internal_mutable_cpumodel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.cpumodel_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE InfoBody::release_cpumodel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:grpcagent.InfoBody.cpuModel)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.cpumodel_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.cpumodel_.Set("", GetArena());
  }
  return released;
}
inline void InfoBody::set_allocated_cpumodel(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.cpumodel_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.cpumodel_.IsDefault()) {
    _impl_.cpumodel_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:grpcagent.InfoBody.cpuModel)
}

// string execPath = 5;
inline void InfoBody::clear_execpath() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.execpath_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline const ::std::string& InfoBody::execpath() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:grpcagent.InfoBody.execPath)
  return _internal_execpath();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void InfoBody::set_execpath(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  _impl_.execpath_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:grpcagent.InfoBody.execPath)
}
inline ::std::string* PROTOBUF_NONNULL InfoBody::mutable_execpath()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::std::string* _s = _internal_mutable_execpath();
  // @@protoc_insertion_point(field_mutable:grpcagent.InfoBody.execPath)
  return _s;
}
inline const ::std::string& InfoBody::_internal_execpath() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.execpath_.Get();
}
inline void InfoBody::_internal_set_execpath(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.execpath_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL InfoBody::_internal_mutable_execpath() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.execpath_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE InfoBody::release_execpath() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:grpcagent.InfoBody.execPath)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000010U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  auto* released = _impl_.execpath_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.execpath_.Set("", GetArena());
  }
  return released;
}
inline void InfoBody::set_allocated_execpath(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }
  _impl_.execpath_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.execpath_.IsDefault()) {
    _impl_.execpath_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:grpcagent.InfoBody.execPath)
}

// string hostname = 6;
inline void InfoBody::clear_hostname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hostname_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline const ::std::string& InfoBody::hostname() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:grpcagent.InfoBody.hostname)
  return _internal_hostname();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void InfoBody::set_hostname(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  _impl_.hostname_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:grpcagent.InfoBody.hostname)
}
inline ::std::string* PROTOBUF_NONNULL InfoBody::mutable_hostname()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  ::std::string* _s = _internal_mutable_hostname();
  // @@protoc_insertion_point(field_mutable:grpcagent.InfoBody.hostname)
  return _s;
}
inline const ::std::string& InfoBody::_internal_hostname() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.hostname_.Get();
}
inline void InfoBody::_internal_set_hostname(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hostname_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL InfoBody::_internal_mutable_hostname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.hostname_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE InfoBody::release_hostname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:grpcagent.InfoBody.hostname)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000020U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
  auto* released = _impl_.hostname_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.hostname_.Set("", GetArena());
  }
  return released;
}
inline void InfoBody::set_allocated_hostname(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
  }
  _impl_.hostname_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.hostname_.IsDefault()) {
    _impl_.hostname_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:grpcagent.InfoBody.hostname)
}

// string id = 7;
inline void InfoBody::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline const ::std::string& InfoBody::id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:grpcagent.InfoBody.id)
  return _internal_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void InfoBody::set_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  _impl_.id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:grpcagent.InfoBody.id)
}
inline ::std::string* PROTOBUF_NONNULL InfoBody::mutable_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  ::std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:grpcagent.InfoBody.id)
  return _s;
}
inline const ::std::string& InfoBody::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_.Get();
}
inline void InfoBody::_internal_set_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL InfoBody::_internal_mutable_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE InfoBody::release_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:grpcagent.InfoBody.id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000040U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
  auto* released = _impl_.id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.id_.Set("", GetArena());
  }
  return released;
}
inline void InfoBody::set_allocated_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
  }
  _impl_.id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:grpcagent.InfoBody.id)
}

// string main = 8;
inline void InfoBody::clear_main() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.main_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline const ::std::string& InfoBody::main() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:grpcagent.InfoBody.main)
  return _internal_main();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void InfoBody::set_main(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  _impl_.main_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:grpcagent.InfoBody.main)
}
inline ::std::string* PROTOBUF_NONNULL InfoBody::mutable_main()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  ::std::string* _s = _internal_mutable_main();
  // @@protoc_insertion_point(field_mutable:grpcagent.InfoBody.main)
  return _s;
}
inline const ::std::string& InfoBody::_internal_main() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.main_.Get();
}
inline void InfoBody::_internal_set_main(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.main_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL InfoBody::_internal_mutable_main() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.main_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE InfoBody::release_main() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:grpcagent.InfoBody.main)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000080U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000080U);
  auto* released = _impl_.main_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.main_.Set("", GetArena());
  }
  return released;
}
inline void InfoBody::set_allocated_main(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000080U);
  }
  _impl_.main_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.main_.IsDefault()) {
    _impl_.main_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:grpcagent.InfoBody.main)
}

// string nodeEnv = 9;
inline void InfoBody::clear_nodeenv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nodeenv_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000100U);
}
inline const ::std::string& InfoBody::nodeenv() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:grpcagent.InfoBody.nodeEnv)
  return _internal_nodeenv();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void InfoBody::set_nodeenv(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  _impl_.nodeenv_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:grpcagent.InfoBody.nodeEnv)
}
inline ::std::string* PROTOBUF_NONNULL InfoBody::mutable_nodeenv()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  ::std::string* _s = _internal_mutable_nodeenv();
  // @@protoc_insertion_point(field_mutable:grpcagent.InfoBody.nodeEnv)
  return _s;
}
inline const ::std::string& InfoBody::_internal_nodeenv() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nodeenv_.Get();
}
inline void InfoBody::_internal_set_nodeenv(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nodeenv_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL InfoBody::_internal_mutable_nodeenv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.nodeenv_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE InfoBody::release_nodeenv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:grpcagent.InfoBody.nodeEnv)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000100U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000100U);
  auto* released = _impl_.nodeenv_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.nodeenv_.Set("", GetArena());
  }
  return released;
}
inline void InfoBody::set_allocated_nodeenv(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000100U);
  }
  _impl_.nodeenv_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.nodeenv_.IsDefault()) {
    _impl_.nodeenv_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:grpcagent.InfoBody.nodeEnv)
}

// uint32 pid = 10;
inline void InfoBody::clear_pid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pid_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00001000U);
}
inline ::uint32_t InfoBody::pid() const {
  // @@protoc_insertion_point(field_get:grpcagent.InfoBody.pid)
  return _internal_pid();
}
inline void InfoBody::set_pid(::uint32_t value) {
  _internal_set_pid(value);
  SetHasBit(_impl_._has_bits_[0], 0x00001000U);
  // @@protoc_insertion_point(field_set:grpcagent.InfoBody.pid)
}
inline ::uint32_t InfoBody::_internal_pid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pid_;
}
inline void InfoBody::_internal_set_pid(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pid_ = value;
}

// string platform = 11;
inline void InfoBody::clear_platform() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.platform_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000200U);
}
inline const ::std::string& InfoBody::platform() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:grpcagent.InfoBody.platform)
  return _internal_platform();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void InfoBody::set_platform(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000200U);
  _impl_.platform_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:grpcagent.InfoBody.platform)
}
inline ::std::string* PROTOBUF_NONNULL InfoBody::mutable_platform()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000200U);
  ::std::string* _s = _internal_mutable_platform();
  // @@protoc_insertion_point(field_mutable:grpcagent.InfoBody.platform)
  return _s;
}
inline const ::std::string& InfoBody::_internal_platform() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.platform_.Get();
}
inline void InfoBody::_internal_set_platform(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.platform_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL InfoBody::_internal_mutable_platform() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.platform_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE InfoBody::release_platform() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:grpcagent.InfoBody.platform)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000200U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000200U);
  auto* released = _impl_.platform_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.platform_.Set("", GetArena());
  }
  return released;
}
inline void InfoBody::set_allocated_platform(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000200U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000200U);
  }
  _impl_.platform_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.platform_.IsDefault()) {
    _impl_.platform_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:grpcagent.InfoBody.platform)
}

// uint64 processStart = 12;
inline void InfoBody::clear_processstart() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.processstart_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00002000U);
}
inline ::uint64_t InfoBody::processstart() const {
  // @@protoc_insertion_point(field_get:grpcagent.InfoBody.processStart)
  return _internal_processstart();
}
inline void InfoBody::set_processstart(::uint64_t value) {
  _internal_set_processstart(value);
  SetHasBit(_impl_._has_bits_[0], 0x00002000U);
  // @@protoc_insertion_point(field_set:grpcagent.InfoBody.processStart)
}
inline ::uint64_t InfoBody::_internal_processstart() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.processstart_;
}
inline void InfoBody::_internal_set_processstart(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.processstart_ = value;
}

// repeated string tags = 13;
inline int InfoBody::_internal_tags_size() const {
  return _internal_tags().size();
}
inline int InfoBody::tags_size() const {
  return _internal_tags_size();
}
inline void InfoBody::clear_tags() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tags_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::std::string* PROTOBUF_NONNULL InfoBody::add_tags()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_tags()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add_mutable:grpcagent.InfoBody.tags)
  return _s;
}
inline const ::std::string& InfoBody::tags(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:grpcagent.InfoBody.tags)
  return _internal_tags().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL InfoBody::mutable_tags(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:grpcagent.InfoBody.tags)
  return _internal_mutable_tags()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void InfoBody::set_tags(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_tags()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:grpcagent.InfoBody.tags)
}
template <typename Arg_, typename... Args_>
inline void InfoBody::add_tags(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_tags(), ::std::forward<Arg_>(value),
      args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:grpcagent.InfoBody.tags)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& InfoBody::tags()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:grpcagent.InfoBody.tags)
  return _internal_tags();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
InfoBody::mutable_tags() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:grpcagent.InfoBody.tags)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_tags();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
InfoBody::_internal_tags() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tags_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
InfoBody::_internal_mutable_tags() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.tags_;
}

// uint64 totalMem = 14;
inline void InfoBody::clear_totalmem() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.totalmem_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00004000U);
}
inline ::uint64_t InfoBody::totalmem() const {
  // @@protoc_insertion_point(field_get:grpcagent.InfoBody.totalMem)
  return _internal_totalmem();
}
inline void InfoBody::set_totalmem(::uint64_t value) {
  _internal_set_totalmem(value);
  SetHasBit(_impl_._has_bits_[0], 0x00004000U);
  // @@protoc_insertion_point(field_set:grpcagent.InfoBody.totalMem)
}
inline ::uint64_t InfoBody::_internal_totalmem() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.totalmem_;
}
inline void InfoBody::_internal_set_totalmem(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.totalmem_ = value;
}

// map<string, string> versions = 15;
inline int InfoBody::_internal_versions_size() const {
  return _internal_versions().size();
}
inline int InfoBody::versions_size() const {
  return _internal_versions_size();
}
inline void InfoBody::clear_versions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.versions_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00010000U);
}
inline const ::google::protobuf::Map<::std::string, ::std::string>& InfoBody::_internal_versions() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.versions_.GetMap();
}
inline const ::google::protobuf::Map<::std::string, ::std::string>& InfoBody::versions() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:grpcagent.InfoBody.versions)
  return _internal_versions();
}
inline ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL InfoBody::_internal_mutable_versions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.versions_.MutableMap();
}
inline ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL InfoBody::mutable_versions()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00010000U);
  // @@protoc_insertion_point(field_mutable_map:grpcagent.InfoBody.versions)
  return _internal_mutable_versions();
}

// uint32 kernelVersion = 16;
inline void InfoBody::clear_kernelversion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.kernelversion_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00008000U);
}
inline ::uint32_t InfoBody::kernelversion() const {
  // @@protoc_insertion_point(field_get:grpcagent.InfoBody.kernelVersion)
  return _internal_kernelversion();
}
inline void InfoBody::set_kernelversion(::uint32_t value) {
  _internal_set_kernelversion(value);
  SetHasBit(_impl_._has_bits_[0], 0x00008000U);
  // @@protoc_insertion_point(field_set:grpcagent.InfoBody.kernelVersion)
}
inline ::uint32_t InfoBody::_internal_kernelversion() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.kernelversion_;
}
inline void InfoBody::_internal_set_kernelversion(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.kernelversion_ = value;
}

// optional string appVersion = 17;
inline bool InfoBody::has_appversion() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000400U);
  return value;
}
inline void InfoBody::clear_appversion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.appversion_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000400U);
}
inline const ::std::string& InfoBody::appversion() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:grpcagent.InfoBody.appVersion)
  return _internal_appversion();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void InfoBody::set_appversion(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000400U);
  _impl_.appversion_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:grpcagent.InfoBody.appVersion)
}
inline ::std::string* PROTOBUF_NONNULL InfoBody::mutable_appversion()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000400U);
  ::std::string* _s = _internal_mutable_appversion();
  // @@protoc_insertion_point(field_mutable:grpcagent.InfoBody.appVersion)
  return _s;
}
inline const ::std::string& InfoBody::_internal_appversion() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.appversion_.Get();
}
inline void InfoBody::_internal_set_appversion(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.appversion_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL InfoBody::_internal_mutable_appversion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.appversion_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE InfoBody::release_appversion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:grpcagent.InfoBody.appVersion)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000400U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000400U);
  auto* released = _impl_.appversion_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.appversion_.Set("", GetArena());
  }
  return released;
}
inline void InfoBody::set_allocated_appversion(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000400U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000400U);
  }
  _impl_.appversion_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.appversion_.IsDefault()) {
    _impl_.appversion_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:grpcagent.InfoBody.appVersion)
}

// -------------------------------------------------------------------

// InfoEvent

// .grpcagent.CommonResponse common = 1;
inline bool InfoEvent::has_common() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.common_ != nullptr);
  return value;
}
inline const ::grpcagent::CommonResponse& InfoEvent::_internal_common() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::grpcagent::CommonResponse* p = _impl_.common_;
  return p != nullptr ? *p : reinterpret_cast<const ::grpcagent::CommonResponse&>(::grpcagent::_CommonResponse_default_instance_);
}
inline const ::grpcagent::CommonResponse& InfoEvent::common() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:grpcagent.InfoEvent.common)
  return _internal_common();
}
inline void InfoEvent::unsafe_arena_set_allocated_common(
    ::grpcagent::CommonResponse* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.common_);
  }
  _impl_.common_ = reinterpret_cast<::grpcagent::CommonResponse*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:grpcagent.InfoEvent.common)
}
inline ::grpcagent::CommonResponse* PROTOBUF_NULLABLE InfoEvent::release_common() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::grpcagent::CommonResponse* released = _impl_.common_;
  _impl_.common_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::grpcagent::CommonResponse* PROTOBUF_NULLABLE InfoEvent::unsafe_arena_release_common() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:grpcagent.InfoEvent.common)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::grpcagent::CommonResponse* temp = _impl_.common_;
  _impl_.common_ = nullptr;
  return temp;
}
inline ::grpcagent::CommonResponse* PROTOBUF_NONNULL InfoEvent::_internal_mutable_common() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.common_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::grpcagent::CommonResponse>(GetArena());
    _impl_.common_ = reinterpret_cast<::grpcagent::CommonResponse*>(p);
  }
  return _impl_.common_;
}
inline ::grpcagent::CommonResponse* PROTOBUF_NONNULL InfoEvent::mutable_common()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::grpcagent::CommonResponse* _msg = _internal_mutable_common();
  // @@protoc_insertion_point(field_mutable:grpcagent.InfoEvent.common)
  return _msg;
}
inline void InfoEvent::set_allocated_common(::grpcagent::CommonResponse* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.common_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.common_ = reinterpret_cast<::grpcagent::CommonResponse*>(value);
  // @@protoc_insertion_point(field_set_allocated:grpcagent.InfoEvent.common)
}

// .grpcagent.InfoBody body = 2;
inline bool InfoEvent::has_body() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.body_ != nullptr);
  return value;
}
inline void InfoEvent::clear_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.body_ != nullptr) _impl_.body_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::grpcagent::InfoBody& InfoEvent::_internal_body() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::grpcagent::InfoBody* p = _impl_.body_;
  return p != nullptr ? *p : reinterpret_cast<const ::grpcagent::InfoBody&>(::grpcagent::_InfoBody_default_instance_);
}
inline const ::grpcagent::InfoBody& InfoEvent::body() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:grpcagent.InfoEvent.body)
  return _internal_body();
}
inline void InfoEvent::unsafe_arena_set_allocated_body(
    ::grpcagent::InfoBody* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.body_);
  }
  _impl_.body_ = reinterpret_cast<::grpcagent::InfoBody*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:grpcagent.InfoEvent.body)
}
inline ::grpcagent::InfoBody* PROTOBUF_NULLABLE InfoEvent::release_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::grpcagent::InfoBody* released = _impl_.body_;
  _impl_.body_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::grpcagent::InfoBody* PROTOBUF_NULLABLE InfoEvent::unsafe_arena_release_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:grpcagent.InfoEvent.body)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::grpcagent::InfoBody* temp = _impl_.body_;
  _impl_.body_ = nullptr;
  return temp;
}
inline ::grpcagent::InfoBody* PROTOBUF_NONNULL InfoEvent::_internal_mutable_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.body_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::grpcagent::InfoBody>(GetArena());
    _impl_.body_ = reinterpret_cast<::grpcagent::InfoBody*>(p);
  }
  return _impl_.body_;
}
inline ::grpcagent::InfoBody* PROTOBUF_NONNULL InfoEvent::mutable_body()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::grpcagent::InfoBody* _msg = _internal_mutable_body();
  // @@protoc_insertion_point(field_mutable:grpcagent.InfoEvent.body)
  return _msg;
}
inline void InfoEvent::set_allocated_body(::grpcagent::InfoBody* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.body_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.body_ = reinterpret_cast<::grpcagent::InfoBody*>(value);
  // @@protoc_insertion_point(field_set_allocated:grpcagent.InfoEvent.body)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace grpcagent


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // info_2eproto_2epb_2eh
