// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nsolid_service.proto
// Protobuf C++ Version: 7.34.0

#include "nsolid_service.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace grpcagent {

inline constexpr EventResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        error_message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
constexpr EventResponse::EventResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(EventResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct EventResponseDefaultTypeInternal {
  constexpr EventResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EventResponseDefaultTypeInternal() {}
  union {
    EventResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EventResponseDefaultTypeInternal _EventResponse_default_instance_;
}  // namespace grpcagent
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_nsolid_5fservice_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_nsolid_5fservice_2eproto = nullptr;
const ::uint32_t
    TableStruct_nsolid_5fservice_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::grpcagent::EventResponse, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::grpcagent::EventResponse, _impl_.error_message_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::grpcagent::EventResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::grpcagent::_EventResponse_default_instance_._instance,
};
const char descriptor_table_protodef_nsolid_5fservice_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024nsolid_service.proto\022\tgrpcagent\032\013asset"
    ".proto\032\022blocked_loop.proto\032\rcommand.prot"
    "o\032\nexit.proto\032\ninfo.proto\032\rmetrics.proto"
    "\032\016packages.proto\032\021reconfigure.proto\032\021sou"
    "rce_code.proto\032\023startup_times.proto\"&\n\rE"
    "ventResponse\022\025\n\rerror_message\030\001 \001(\t2\371\006\n\r"
    "NSolidService\022F\n\007Command\022\032.grpcagent.Com"
    "mandResponse\032\031.grpcagent.CommandRequest\""
    "\000(\0010\001\022=\n\013ExportAsset\022\020.grpcagent.Asset\032\030"
    ".grpcagent.EventResponse\"\000(\001\022I\n\027ExportCo"
    "ntinuousProfile\022\020.grpcagent.Asset\032\030.grpc"
    "agent.EventResponse\"\000(\001\022>\n\nExportExit\022\024."
    "grpcagent.ExitEvent\032\030.grpcagent.EventRes"
    "ponse\"\000\022>\n\nExportInfo\022\024.grpcagent.InfoEv"
    "ent\032\030.grpcagent.EventResponse\"\000\022D\n\rExpor"
    "tMetrics\022\027.grpcagent.MetricsEvent\032\030.grpc"
    "agent.EventResponse\"\000\022F\n\016ExportPackages\022"
    "\030.grpcagent.PackagesEvent\032\030.grpcagent.Ev"
    "entResponse\"\000\022L\n\021ExportBlockedLoop\022\033.grp"
    "cagent.BlockedLoopEvent\032\030.grpcagent.Even"
    "tResponse\"\000\022P\n\023ExportUnblockedLoop\022\035.grp"
    "cagent.UnblockedLoopEvent\032\030.grpcagent.Ev"
    "entResponse\"\000\022L\n\021ExportReconfigure\022\033.grp"
    "cagent.ReconfigureEvent\032\030.grpcagent.Even"
    "tResponse\"\000\022J\n\020ExportSourceCode\022\032.grpcag"
    "ent.SourceCodeEvent\032\030.grpcagent.EventRes"
    "ponse\"\000\022N\n\022ExportStartupTimes\022\034.grpcagen"
    "t.StartupTimesEvent\032\030.grpcagent.EventRes"
    "ponse\"\000b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_nsolid_5fservice_2eproto_deps[10] = {
        &::descriptor_table_asset_2eproto,
        &::descriptor_table_blocked_5floop_2eproto,
        &::descriptor_table_command_2eproto,
        &::descriptor_table_exit_2eproto,
        &::descriptor_table_info_2eproto,
        &::descriptor_table_metrics_2eproto,
        &::descriptor_table_packages_2eproto,
        &::descriptor_table_reconfigure_2eproto,
        &::descriptor_table_source_5fcode_2eproto,
        &::descriptor_table_startup_5ftimes_2eproto,
};
static ::absl::once_flag descriptor_table_nsolid_5fservice_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_nsolid_5fservice_2eproto = {
    false,
    false,
    1135,
    descriptor_table_protodef_nsolid_5fservice_2eproto,
    "nsolid_service.proto",
    &descriptor_table_nsolid_5fservice_2eproto_once,
    descriptor_table_nsolid_5fservice_2eproto_deps,
    10,
    1,
    schemas,
    file_default_instances,
    TableStruct_nsolid_5fservice_2eproto::offsets,
    file_level_enum_descriptors_nsolid_5fservice_2eproto,
    file_level_service_descriptors_nsolid_5fservice_2eproto,
};
namespace grpcagent {
// ===================================================================

class EventResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<EventResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(EventResponse, _impl_._has_bits_);
};

EventResponse::EventResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, EventResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:grpcagent.EventResponse)
}
PROTOBUF_NDEBUG_INLINE EventResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::grpcagent::EventResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        error_message_(arena, from.error_message_) {}

EventResponse::EventResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const EventResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, EventResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  EventResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:grpcagent.EventResponse)
}
PROTOBUF_NDEBUG_INLINE EventResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        error_message_(arena) {}

inline void EventResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
EventResponse::~EventResponse() {
  // @@protoc_insertion_point(destructor:grpcagent.EventResponse)
  SharedDtor(*this);
}
inline void EventResponse::SharedDtor(MessageLite& self) {
  EventResponse& this_ = static_cast<EventResponse&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.error_message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL EventResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) EventResponse(arena);
}
constexpr auto EventResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(EventResponse),
                                            alignof(EventResponse));
}
constexpr auto EventResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_EventResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &EventResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<EventResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &EventResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<EventResponse>(), &EventResponse::ByteSizeLong,
              &EventResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(EventResponse, _impl_._cached_size_),
          false,
      },
      &EventResponse::kDescriptorMethods,
      &descriptor_table_nsolid_5fservice_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull EventResponse_class_data_ =
        EventResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
EventResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&EventResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(EventResponse_class_data_.tc_table);
  return EventResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 45, 2>
EventResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(EventResponse, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    EventResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::grpcagent::EventResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string error_message = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(EventResponse, _impl_.error_message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string error_message = 1;
    {PROTOBUF_FIELD_OFFSET(EventResponse, _impl_.error_message_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\27\15\0\0\0\0\0\0"
    "grpcagent.EventResponse"
    "error_message"
  }},
};
PROTOBUF_NOINLINE void EventResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:grpcagent.EventResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.error_message_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL EventResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const EventResponse& this_ = static_cast<const EventResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL EventResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const EventResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:grpcagent.EventResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string error_message = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_error_message().empty()) {
      const ::std::string& _s = this_._internal_error_message();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "grpcagent.EventResponse.error_message");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:grpcagent.EventResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t EventResponse::ByteSizeLong(const MessageLite& base) {
  const EventResponse& this_ = static_cast<const EventResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t EventResponse::ByteSizeLong() const {
  const EventResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:grpcagent.EventResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string error_message = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_error_message().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_error_message());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void EventResponse::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<EventResponse*>(&to_msg);
  auto& from = static_cast<const EventResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:grpcagent.EventResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!from._internal_error_message().empty()) {
      _this->_internal_set_error_message(from._internal_error_message());
    } else {
      if (_this->_impl_.error_message_.IsDefault()) {
        _this->_internal_set_error_message("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void EventResponse::CopyFrom(const EventResponse& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:grpcagent.EventResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EventResponse::InternalSwap(EventResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.error_message_, &other->_impl_.error_message_, arena);
}

::google::protobuf::Metadata EventResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace grpcagent
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_nsolid_5fservice_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
