name: Test macOS

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - .mailmap
      - '**.md'
      - AUTHORS
      - doc/**
      - .github/**
      - '!.github/workflows/test-macos.yml'
  push:
    branches:
      - main
      - canary
      - v[0-9]+.x-staging
      - v[0-9]+.x
    paths-ignore:
      - .mailmap
      - '**.md'
      - AUTHORS
      - doc/**
      - .github/**
      - '!.github/workflows/test-macos.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.12'
  FLAKY_TESTS: keep_retrying

permissions:
  contents: read

jobs:
  test-macOS:
    if: github.event.pull_request.draft == false
    runs-on: macos-14
    env:
      CC: sccache gcc
      CXX: sccache g++
      SCCACHE_GHA_ENABLED: 'true'
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
        with:
          persist-credentials: false
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3  # v5.2.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Set up sccache
        uses: mozilla-actions/sccache-action@89e9040de88b577a072e3760aaf59f585da083af  # v0.0.5
        with:
          version: v0.8.1
      - name: Environment Information
        run: npx envinfo
      # The `npm ci` for this step fails a lot as part of the Test step. Run it
      # now so that we don't have to wait 2 hours for the Build step to pass
      # first before that failure happens. (And if there's something about
      # `make run-ci -j3` that is causing the failure and the failure doesn't
      # happen anymore running this step here first, that's also useful
      # information.)
      - name: tools/doc/node_modules workaround
        run: make tools/doc/node_modules
      # This is needed due to https://github.com/nodejs/build/issues/3878
      - name: Cleanup
        run: |
          echo "::group::Free space before cleanup"
          df -h
          echo "::endgroup::"
          echo "::group::Cleaned Files"

          sudo rm -rfv /Users/runner/Library/Android/sdk

          echo "::endgroup::"
          echo "::group::Free space after cleanup"
          df -h
          echo "::endgroup::"
      - name: Build
        run: make build-ci -j$(getconf _NPROCESSORS_ONLN) V=1 CONFIG_FLAGS="--error-on-warn"
      - name: Test
        run: make run-ci -j$(getconf _NPROCESSORS_ONLN) V=1 TEST_CI_ARGS="-p actions --node-args='--test-reporter=spec' --node-args='--test-reporter-destination=stdout' --measure-flakiness 9"
